name: songbing
version: 1

libraries:
- name: "webpy"
  version: "0.36"

- name: "backports"
  version: "1.0rc1"

- name: "bleach"
  version: "1.5.0"

- name: "funcsigs"
  version: "1.0.2"

- name: "html5lib"
  version: "0.9999999"

- name: "markdown"
  version: "2.6.8"

- name: "mock"
  version: "2.0.0"

- name: "numpy"
  version: "1.13.1"

- name: "pbr"
  version: "3.1.1"

- name: "protobuf"
  version: "3.3.0"

- name: "setuptools"
  version: "36.2.0"

- name: "six"
  version: "1.10.0"

- name: "tensorflow"
  version: "1.2.1"

- name: "werkzeug"
  version: "0.12.2"

- name: "wheel"
  version: "0.29.0"